### ISSUE TITLE
ILMbase errors

### ISSUE THREAD

**Issue by ahemberger** [alicevision/QtAliceVision#15]
Hi, trying to run cmake and I see errors about ilmbase. 

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Imath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IlmThread" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IexMath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Iex" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Half" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Imath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IlmThread" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IexMath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Iex" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Half" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Imath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IlmThread" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IexMath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Iex" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Half" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Imath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IlmThread" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::IexMath" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Iex" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

CMake Error at H:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:499 (_add_library):
  Target "qtAliceVisionPlugin" links to target "IlmBase::Half" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:23 (add_library)

**Comment by fabiencastan** [comment]
Hi,
I'm not sure where it is not properly propagated.
In the meantime, you could add this to the root CMakeLists.txt:
```
# AliceVision dependency
find_package(IlmBase REQUIRED)
find_package(AliceVision REQUIRED)
```

**Comment by fabiencastan** [comment]
A [find_dependency](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html) is probably missing from one of the config file.

**Comment by ahemberger** [comment]
Woop! This totally worked, thanks so much @fabiencastan!
